### ISSUE TITLE
VOMS api with BC 1.50

### ISSUE THREAD

**Issue by romainreuillon** [italiangrid/voms-api-java#17]
I am using voms-api-java in a lib called [gridscale](https://github.com/openmole/gridscale) however the version is very old. I would like to update to version which is uptodate but it should be based on BC 1.50. I saw that you've a branch based on BC 1.50, but this branch seems not maintained right now. Do you plan to develop this branch further? Could you deploy an up to date snapshot with the fixes of the main branch? What is the schedule to release 3.1?

**Comment by andreaceccanti** [comment]
Hello Romain,
the current plan is to release 3.1 by september (completing the port to canl 2/bc 1.52).

**Comment by romainreuillon** [comment]
Great news, thx.

**Comment by andreaceccanti** [comment]
3.1.0.rc0 is in maven central since last november, closing this.
3.1.0, providing minor fixes and improvements, will come shortly, but you can rely on what's already available in central.

thanx
