### ISSUE TITLE
VOMS AC validation failing (LSC and AC), but proxy get created

### ISSUE THREAD

**Issue by egazzarr** [italiangrid/voms-api-java#31]
Good afternoon, 

We are trying to generate a proxy for the escape VO and get the following warnings when running `voms-proxy-init --cert ./client.crt --key ./client.key --out x509up_escape --voms escape`

```
Contacting voms-escape.cloud.cnaf.infn.it:15000 [/DC=org/DC=terena/DC=tcs/C=IT/ST=Roma/O=Istituto Nazionale di Fisica Nucleare - INFN/OU=CNAF/CN=voms-escape.cloud.cnaf.infn.it] "escape"...
Remote VOMS server contacted succesfully.


WARNING: VOMS AC validation for VO escape failed for the following reasons:
         LSC validation failed: LSC chain description does not match AA certificate chain embedded in the VOMS AC!
         AC signature verification failure: no valid VOMS server credential found.

Created proxy in x509up_escape.
```
Would you know what to do to manage these, and why this has suddenly started happening about a week ago?

Thanks !

**Comment by rmiccoli** [comment]
Hi Elena,

that's because one week ago the voms-escape certificate has been renewed. We noticed a change in the DN, in particular the Organization Name (Istituto Nazionale di Fisica Nucleare) differs from the old one; so the VOMS AC validation fails.

**Comment by egazzarr** [comment]
Hi Roberta,

Thanks for clarifying. I did try to change the host certificate for our
rucio server on October the 10th, did you notice something from then? The
certificate should be exactly the same as before though, and I am not sure
the VOMS are connected to that. The robot certificate used to generate the
voms-proxy is instead unchanged.. Is there anything more specific we should
do on our side to fix this?

Thanks!

Elena

*Elena Gazzarrini*
Computing Fellow, Data Engineer for Open Science
*CERN IT Department / GOV-ENG Group*

**Comment by egazzarr** [comment]
Ciao Roberta,

Thanks for the answer, but I have changed the file and I get the following
error:


*LSC file parsing error: Malformed LSC file (vo=escape,
host=voms-escape.cloud.cnaf.infn.it
<http://voms-escape.cloud.cnaf.infn.it>): Odd number of distinguished name
entries.org.italiangrid.voms.VOMSError: LSC file parsing error: Malformed
LSC file (vo=escape, host=voms-escape.cloud.cnaf.infn.it
<http://voms-escape.cloud.cnaf.infn.it>): Odd number of distinguished name
entries.*

Strange, it works for you?

Thanks!

Elena
*Elena Gazzarrini*
Computing Fellow, Data Engineer for Open Science
*CERN IT Department / GOV-ENG Group*

**Comment by federicaagostini** [comment]
Hi Elena, sorry that we missed the first `/` of the VOMS-aa ESCAPE server DN.
If you try the new configuration (lsc) it should work now -- the documentation has been [updated](https://github.com/indigo-iam/escape-docs/commit/675d6e128ba3bfdbb0cf844ff4667ea84fa20383) accordingly.

**Comment by egazzarr** [comment]
Ok grazie mille Federica!
Elena
*Elena Gazzarrini*
Computing Fellow, Data Engineer for Open Science
*CERN IT Department / GOV-ENG Group*
