### ISSUE TITLE
Tests fail outside Central European time zone

### ISSUE THREAD

**Issue by ellert** [italiangrid/voms-api-java#8]
The tests testExpiredAACertValidationFailure and testRevokedAACertValidationFailure in the source file src/test/java/org/italiangrid/voms/test/ac/TestACGeneration.java only succeed when run on a computer in the Central European time zone.

The reason for this is that the expected error messages from canl contain timestamps:

"Certificate has expired on: Fri Dec 02 01:00:00 CET 2011"
"Certificate was revoked at: Wed Sep 26 17:25:24 CEST 2012, the reason reported is: unspecified"

However, when run outside of the Central European time zone, the timestamps in the error messages from canl will be written in other time zones and the exact match to the expected error string in the Central European time zone will fail.

**Comment by andreaceccanti** [comment]
This should be fixed in the latest release. The APIs build fine on drone.io and travis which are in other timezones.
